import { KPI } from '../types';

export const kpiLibrary: KPI[] = [
  {
    id: 'revenue',
    name: 'Total Revenue',
    category: 'Financial',
    description: 'Total income generated from business operations.',
    formula: 'sum(income)',
    format: 'currency',
    goodDirection: 'up',
    chartType: 'area',
    applicableIndustries: ['All'],
  },
  {
    id: 'net_profit',
    name: 'Net Profit',
    category: 'Financial',
    description: 'Actual profit after working expenses.',
    formula: 'revenue - expenses',
    format: 'currency',
    goodDirection: 'up',
    chartType: 'bar',
    applicableIndustries: ['All'],
  },
  {
    id: 'net_margin',
    name: 'Net Profit Margin',
    category: 'Financial',
    description: 'Percentage of revenue remaining as profit.',
    formula: '(net_profit / revenue) * 100',
    format: 'percentage',
    goodDirection: 'up',
    chartType: 'area',
    applicableIndustries: ['All'],
  },
  {
    id: 'cash_balance',
    name: 'Cash Balance',
    category: 'Cash Flow',
    description: 'Total cash on hand.',
    formula: 'sum(cash_accounts)',
    format: 'currency',
    goodDirection: 'up',
    chartType: 'area',
    applicableIndustries: ['All'],
  },
  {
    id: 'runway',
    name: 'Cash Runway (Months)',
    category: 'Cash Flow',
    description: 'How long current cash will last at current burn rate.',
    formula: 'cash_balance / monthly_burn',
    format: 'number',
    goodDirection: 'up',
    chartType: 'metric',
    applicableIndustries: ['All'],
  },
  {
    id: 'health_score',
    name: 'Client Health Score',
    category: 'Advisory',
    description: 'Aggregated health of the client firm.',
    formula: 'weighted_average',
    format: 'number',
    goodDirection: 'up',
    chartType: 'metric',
    applicableIndustries: ['CPA Client'],
  }
];
